DROP TABLE IF EXISTS PARSER_CONFIG;
DROP TABLE IF EXISTS EXPORT_CONFIG;
DROP TABLE IF EXISTS MAIL_CONNECTION_CONFIG;
DROP TABLE IF EXISTS CLIENTE;

CREATE TABLE PARSER_CONFIG (
	ID INT NOT NULL AUTO_INCREMENT,
	FIELD_NAME VARCHAR(255) NOT NULL,
	FIELD_START_PATTERN VARCHAR(255),
    FIELD_END_PATTERN VARCHAR(255),
	PRIMARY KEY(ID)
);

CREATE TABLE EXPORT_CONFIG (
	ID INT NOT NULL AUTO_INCREMENT,
	PARSER_NAME VARCHAR(255) NOT NULL,
	TABLE_NAME VARCHAR(255) NOT NULL,
    COLUMN_NAME VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE MAIL_CONNECTION_CONFIG (
	ID INT NOT NULL AUTO_INCREMENT,
	CONFIG_NAME VARCHAR(255) NOT NULL,
	CONFIG_VALUE VARCHAR(255),
	PRIMARY KEY(ID)
);

CREATE TABLE CLIENTE(
	ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255),
	TELEFONE VARCHAR(255),
    EMAIL VARCHAR(255),
    ENDERECO VARCHAR(255),
	PRIMARY KEY(ID)
);