--CREATE DATABASE JMIC;
--USE JMIC;

-----------------------------------------------------------------------------------
    
CREATE TABLE JMIC.PARSER_CONFIG (
	ID INT NOT NULL AUTO_INCREMENT,
	FIELD_NAME VARCHAR(255) NOT NULL,
	FIELD_START_PATTERN VARCHAR(255),
    FIELD_END_PATTERN VARCHAR(255),
	PRIMARY KEY(ID)
);

INSERT INTO JMIC.PARSER_CONFIG (FIELD_NAME, FIELD_START_PATTERN, FIELD_END_PATTERN)
	VALUES ('CLIENT_NAME','*Nome:*','\r');

INSERT INTO JMIC.PARSER_CONFIG (FIELD_NAME, FIELD_START_PATTERN, FIELD_END_PATTERN)
	VALUES ('CLIENT_PHONE','*Telefone:*','\r');

INSERT INTO JMIC.PARSER_CONFIG (FIELD_NAME, FIELD_START_PATTERN, FIELD_END_PATTERN)
	VALUES ('CLIENT_EMAIL','*Email:*','\r');
    
INSERT INTO JMIC.PARSER_CONFIG (FIELD_NAME, FIELD_START_PATTERN, FIELD_END_PATTERN)
	VALUES ('CLIENT_LOCATION','*Local:*','\r');

INSERT INTO JMIC.PARSER_CONFIG (FIELD_NAME, FIELD_START_PATTERN, FIELD_END_PATTERN)
	VALUES ('SERVICE_DESCRIPTION','*Qual é o serviço?*','*É necessário algum conhecimento específico?*');
    
INSERT INTO JMIC.PARSER_CONFIG (FIELD_NAME, FIELD_START_PATTERN, FIELD_END_PATTERN)
	VALUES ('SKILLS_NEEDED','*É necessário algum conhecimento específico?*','*Para quando você precisa deste serviço?*');
    
INSERT INTO JMIC.PARSER_CONFIG (FIELD_NAME, FIELD_START_PATTERN, FIELD_END_PATTERN)
	VALUES ('DEADLINE','*Para quando você precisa deste serviço?*','*Informações Adicionais*');
    
INSERT INTO JMIC.PARSER_CONFIG (FIELD_NAME, FIELD_START_PATTERN, FIELD_END_PATTERN)
	VALUES ('ADDITIONAL_INFO','*Informações Adicionais*','[image: Dont forget]');

COMMIT;

-----------------------------------------------------------------------------------

CREATE TABLE JMIC.MAIL_CONNECTION_CONFIG (
	ID INT NOT NULL AUTO_INCREMENT,
	CONFIG_NAME VARCHAR(255) NOT NULL,
	CONFIG_VALUE VARCHAR(255),
	PRIMARY KEY(ID)
);

INSERT INTO JMIC.MAIL_CONNECTION_CONFIG(CONFIG_NAME, CONFIG_VALUE)
	VALUES ('host', 'imap.gmail.com');

INSERT INTO JMIC.MAIL_CONNECTION_CONFIG(CONFIG_NAME, CONFIG_VALUE)
	VALUES ('inboxfolder', 'INBOX');

INSERT INTO JMIC.MAIL_CONNECTION_CONFIG(CONFIG_NAME, CONFIG_VALUE)
	VALUES ('username', '');
    
INSERT INTO JMIC.MAIL_CONNECTION_CONFIG(CONFIG_NAME, CONFIG_VALUE)
	VALUES ('password', '');

INSERT INTO JMIC.MAIL_CONNECTION_CONFIG(CONFIG_NAME, CONFIG_VALUE)
	VALUES ('mail.store.protocol', 'imaps');
    
INSERT INTO JMIC.MAIL_CONNECTION_CONFIG(CONFIG_NAME, CONFIG_VALUE)
	VALUES ('mail.imap.ssl.enable', 'true');
    
INSERT INTO JMIC.MAIL_CONNECTION_CONFIG(CONFIG_NAME, CONFIG_VALUE)
	VALUES ('mail.imap.socketFactory.class', 'javax.net.ssl.SSLSocketFactory');    

INSERT INTO JMIC.MAIL_CONNECTION_CONFIG(CONFIG_NAME, CONFIG_VALUE)
	VALUES ('mail.imap.socketFactory.class', 'false');

INSERT INTO JMIC.MAIL_CONNECTION_CONFIG(CONFIG_NAME, CONFIG_VALUE)
	VALUES ('mail.imap.socketFactory.port', '993');

INSERT INTO JMIC.MAIL_CONNECTION_CONFIG(CONFIG_NAME, CONFIG_VALUE)
	VALUES ('filter.daysago', '20');

INSERT INTO JMIC.MAIL_CONNECTION_CONFIG(CONFIG_NAME, CONFIG_VALUE)
	VALUES ('filter.sender', '');

INSERT INTO JMIC.MAIL_CONNECTION_CONFIG(CONFIG_NAME, CONFIG_VALUE)
	VALUES ('filter.subject', 'pedido');

INSERT INTO JMIC.MAIL_CONNECTION_CONFIG(CONFIG_NAME, CONFIG_VALUE)
	VALUES ('filter.unread', 'false');

COMMIT;