--CREATE DATABASE JMIC;
--USE JMIC;

CREATE TABLE JMIC.PARSER_CONFIG (
	ID INT NOT NULL AUTO_INCREMENT,
	FIELD_NAME VARCHAR(255) NOT NULL,
	FIELD_START_PATTERN VARCHAR(255),
    FIELD_END_PATTERN VARCHAR(255),
	PRIMARY KEY(ID)
);

INSERT INTO JMIC.PARSER_CONFIG (FIELD_NAME, FIELD_START_PATTERN, FIELD_END_PATTERN)
	VALUES ('CLIENT_NAME','*Nome:*','\r');

INSERT INTO JMIC.PARSER_CONFIG (FIELD_NAME, FIELD_START_PATTERN, FIELD_END_PATTERN)
	VALUES ('CLIENT_PHONE','*Telefone:*','[image:');

INSERT INTO JMIC.PARSER_CONFIG (FIELD_NAME, FIELD_START_PATTERN, FIELD_END_PATTERN)
	VALUES ('CLIENT_EMAIL','*Email:*','\r');
    
INSERT INTO JMIC.PARSER_CONFIG (FIELD_NAME, FIELD_START_PATTERN, FIELD_END_PATTERN)
	VALUES ('CLIENT_LOCATION','*Local:*','\r');

INSERT INTO JMIC.PARSER_CONFIG (FIELD_NAME, FIELD_START_PATTERN, FIELD_END_PATTERN)
	VALUES ('SERVICE_DESCRIPTION','*Qual é o serviço?*','*É necessário algum conhecimento específico?*');
    
INSERT INTO JMIC.PARSER_CONFIG (FIELD_NAME, FIELD_START_PATTERN, FIELD_END_PATTERN)
	VALUES ('SKILLS_NEEDED','*É necessário algum conhecimento específico?*','*Para quando você precisa deste serviço?*');
    
INSERT INTO JMIC.PARSER_CONFIG (FIELD_NAME, FIELD_START_PATTERN, FIELD_END_PATTERN)
	VALUES ('DEADLINE','*Para quando você precisa deste serviço?*','*Informações Adicionais*');
    
INSERT INTO JMIC.PARSER_CONFIG (FIELD_NAME, FIELD_START_PATTERN, FIELD_END_PATTERN)
	VALUES ('ADDITIONAL_INFO','*Informações Adicionais*','[image: Dont forget]');

CREATE TABLE JMIC.MAIL_CONNECTION_CONFIG (
	ID INT NOT NULL AUTO_INCREMENT,
	CONFIG_NAME VARCHAR(255) NOT NULL,
	CONFIG_VALUE VARCHAR(255),
	PRIMARY KEY(ID)
);

INSERT INTO JMIC.MAIL_CONNECTION_CONFIG(CONFIG_NAME, CONFIG_VALUE)
	VALUES ('host', 'imap.gmail.com');

INSERT INTO JMIC.MAIL_CONNECTION_CONFIG(CONFIG_NAME, CONFIG_VALUE)
	VALUES ('inboxfolder', 'INBOX');

INSERT INTO JMIC.MAIL_CONNECTION_CONFIG(CONFIG_NAME, CONFIG_VALUE)
	VALUES ('username', '');
    
INSERT INTO JMIC.MAIL_CONNECTION_CONFIG(CONFIG_NAME, CONFIG_VALUE)
	VALUES ('password', '');

INSERT INTO JMIC.MAIL_CONNECTION_CONFIG(CONFIG_NAME, CONFIG_VALUE)
	VALUES ('mail.store.protocol', 'imaps');
    
INSERT INTO JMIC.MAIL_CONNECTION_CONFIG(CONFIG_NAME, CONFIG_VALUE)
	VALUES ('mail.imap.ssl.enable', 'true');
    
INSERT INTO JMIC.MAIL_CONNECTION_CONFIG(CONFIG_NAME, CONFIG_VALUE)
	VALUES ('mail.imap.socketFactory.class', 'javax.net.ssl.SSLSocketFactory');    

INSERT INTO JMIC.MAIL_CONNECTION_CONFIG(CONFIG_NAME, CONFIG_VALUE)
	VALUES ('mail.imap.socketFactory.class', 'false');

INSERT INTO JMIC.MAIL_CONNECTION_CONFIG(CONFIG_NAME, CONFIG_VALUE)
	VALUES ('mail.imap.socketFactory.port', '993');

INSERT INTO JMIC.MAIL_CONNECTION_CONFIG(CONFIG_NAME, CONFIG_VALUE)
	VALUES ('filter.daysago', '20');

INSERT INTO JMIC.MAIL_CONNECTION_CONFIG(CONFIG_NAME, CONFIG_VALUE)
	VALUES ('filter.sender', '');

INSERT INTO JMIC.MAIL_CONNECTION_CONFIG(CONFIG_NAME, CONFIG_VALUE)
	VALUES ('filter.subject', 'pedido');

INSERT INTO JMIC.MAIL_CONNECTION_CONFIG(CONFIG_NAME, CONFIG_VALUE)
	VALUES ('filter.unread', 'false');

CREATE TABLE JMIC.EXPORT_CONFIG (
	ID INT NOT NULL AUTO_INCREMENT,
	PARSER_NAME VARCHAR(255) NOT NULL,
	TABLE_NAME VARCHAR(255) NOT NULL,
    COLUMN_NAME VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID)
);

INSERT INTO JMIC.EXPORT_CONFIG(PARSER_NAME, TABLE_NAME, COLUMN_NAME)
	VALUES ('CLIENT_NAME', 'SERVICO', 'CLIENTE');

INSERT INTO JMIC.EXPORT_CONFIG(PARSER_NAME, TABLE_NAME, COLUMN_NAME)
	VALUES ('CLIENT_PHONE', 'SERVICO', 'TELEFONE');

INSERT INTO JMIC.EXPORT_CONFIG(PARSER_NAME, TABLE_NAME, COLUMN_NAME)
	VALUES ('CLIENT_EMAIL', 'SERVICO', 'EMAIL');

INSERT INTO JMIC.EXPORT_CONFIG(PARSER_NAME, TABLE_NAME, COLUMN_NAME)
	VALUES ('CLIENT_LOCATION', 'SERVICO', 'ENDERECO');

INSERT INTO JMIC.EXPORT_CONFIG(PARSER_NAME, TABLE_NAME, COLUMN_NAME)
	VALUES ('SERVICE_DESCRIPTION', 'SERVICO', 'DESCRICAO');

INSERT INTO JMIC.EXPORT_CONFIG(PARSER_NAME, TABLE_NAME, COLUMN_NAME)
	VALUES ('SKILLS_NEEDED', 'SERVICO', 'COMPETENCIAS');

INSERT INTO JMIC.EXPORT_CONFIG(PARSER_NAME, TABLE_NAME, COLUMN_NAME)
	VALUES ('DEADLINE', 'SERVICO', 'PRAZO');

INSERT INTO JMIC.EXPORT_CONFIG(PARSER_NAME, TABLE_NAME, COLUMN_NAME)
	VALUES ('ADDITIONAL_INFO', 'SERVICO', 'OBSERVACOES');

CREATE TABLE JMIC.SERVICO(
	ID INT NOT NULL AUTO_INCREMENT,
    CLIENTE VARCHAR(255),
	TELEFONE VARCHAR(255),
    EMAIL VARCHAR(255),
    ENDERECO VARCHAR(255),
    DESCRICAO VARCHAR(255),
    COMPETENCIAS VARCHAR(255),
    PRAZO VARCHAR(255),
    OBSERVACOES VARCHAR(255),
	PRIMARY KEY(ID)
);

COMMIT;